# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: test
    arguments: 'dotnetcore-tests --configuration $(buildConfiguration) --logger trx'
  displayName: 'Executando testes...'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: 'Publicando resultado dos testes...'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
  displayName: 'Publicando arquivos...'

- task: PublishBuildArtifacts@1

- task: AzureRmWebAppDeployment@4
  inputs:
    connectionType: 'AzureRM' 
    azureSubscription: 'Wesley Subscription'
    appType: 'webApp' 
    webAppName: 'webApp-DemoGitHub' 
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
  displayName: 'Realizando deploy...'    